Lesson2
Azmandius21/TestGuru pull request #2
Opened 2022-05-17 13:09 UTC by Azmandius21

2022-05-17 13:44 UTC, VidgarVii requested changes

2022-05-17 13:44 UTC, VidgarVii commented on db/migrate/20220514171603_add_users_name_null_constraint.rb
> +    change_column_null(:users,:name,false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2022-05-17 13:44 UTC, VidgarVii commented on db/migrate/20220514110621_create_answers.rb
> +      t.integer :id_question
1 поля названы не верно. Следуй соглашению
2 нужны не просто поля, а так же внешние ключи. Нет ключей - нет связей

2022-05-17 13:44 UTC, VidgarVii commented on db/schema.rb
> +    t.integer "id_test"
категория не принадлежит тесту. Это категория может иметь сколько угодно тестов

2022-05-17 13:44 UTC, VidgarVii commented on db/schema.rb
> +    t.datetime "updated_at", precision: 6, null: false
для теста нам еще понадобиться автор. Это юзер который создал тест. Давай сделаем это в текущем ПР

2022-05-17 13:55 UTC, Azmandius21 commented on db/migrate/20220514171603_add_users_name_null_constraint.rb
> +    change_column_null(:users,:name,false)
Ага, понял!

2022-05-19 03:31 UTC, Azmandius21 commented on db/migrate/20220514110621_create_answers.rb
> +      t.integer :id_question
поправил названия полей . Вместо 'user' нужно было 'user_id' и так в других полях, которые являются внешними ключами, я правильно понял?

2022-05-19 03:37 UTC, Azmandius21 commented on db/schema.rb
> +    t.integer "id_test"
Это поправил.  Так же по этой таблице возник вопрос: можно же сделать  первичным ключем поле 'level' ?

2022-05-19 03:37 UTC, Azmandius21 commented on db/schema.rb
> +    t.datetime "updated_at", precision: 6, null: false
автора добавил

2022-05-19 06:12 UTC, VidgarVii requested changes

2022-05-19 06:12 UTC, VidgarVii commented on db/migrate/20220514111759_create_users.rb
> +      t.integer :score, default: 0
admin и score не будет использоваться.
Для подсчёта отчок достаточно 1 запроса в базу. Для Админа будем использовать специальный паттерн

2022-05-19 06:12 UTC, VidgarVii commented on db/migrate/20220514110621_create_answers.rb
> +      t.string :user_id, null: false
ответ не принадлежит юзеру. И очень странно, почему string?

2022-05-19 06:12 UTC, VidgarVii commented on db/migrate/20220514110621_create_answers.rb
> +      t.string :body
null: false

2022-05-19 06:12 UTC, VidgarVii commented on db/migrate/20220514110621_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2022-05-19 06:12 UTC, VidgarVii commented on db/migrate/20220514110230_create_questions.rb
> +      t.string :answer, null: false
какие данные будет содержать это поле? Есть целая таблица для ответов

2022-05-19 06:12 UTC, VidgarVii commented on db/migrate/20220514093338_create_tests.rb
> +
тест надо привязать еще к категории.
и как я уже писал для связей нужны внешние ключи для обеспечения ссылочной целостности данных 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

2022-05-19 08:38 UTC, Azmandius21 commented on db/migrate/20220514110230_create_questions.rb
> +      t.string :answer, null: false
это поле я выделил для правильного ответа на вопрос

2022-05-19 14:41 UTC, VidgarVii requested changes

2022-05-19 14:41 UTC, VidgarVii commented on db/migrate/20220514093338_create_tests.rb
> +      t.integer :author_id, null: false
автор это юзер.  Получается так же нужна связь с юзером. Но логику автора и название поле author_id должно остаться

2022-05-19 14:41 UTC, VidgarVii commented on db/migrate/20220514093338_create_tests.rb
> +      t.integer :level, default: 0
null: false

2022-05-20 16:53 UTC, Azmandius21 commented on db/migrate/20220514093338_create_tests.rb
> +      t.integer :author_id, null: false
это нужно сделать через полиморфизм?

2022-05-21 13:35 UTC, VidgarVii requested changes

2022-05-21 13:35 UTC, VidgarVii commented on Test_Guru_db/home_work_on_sqlite3.csv
> +SELECT * FROM tests
файлы  в этой папке  к проекту не относится. Стои их убрать от сюда

2022-05-21 13:35 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали
нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2022-05-21 16:34 UTC, merged

2022-05-21 16:35 UTC, Azmandius21 commented
merge lesson2 to master